### ISSUE TITLE
React Component

### ISSUE THREAD

**Issue by ozeman** [datocms/datocms-search#15]
Hi,

do you plan to transfer this to React component?

Ondra

**Comment by stefanoverna** [comment]
Hi @ozeman, this is meant to be used in very simple websites where the development team is not super-expert. If you know how to use React, then it's extremely easy to build a component around the API, an tailor it to your specific needs!

See the one in our website as an example (it also fetches search results from our community using Discourse API): 
https://www.datocms.com/docs
https://github.com/datocms/new-website/blob/master/components/DocSearch/index.js
