### ISSUE TITLE
DatoCMS Search Widget - Scrolling on mobile not working

### ISSUE THREAD

**Issue by daveharrisonnet** [datocms/datocms-search#9]
So I installed the search widget, configured it and got it working perfectly, hat tip! ;)
HOWEVER...
When viewing my website on a mobile device (firefox most recent on android) [tried a few others, chrome, opera]. When the widget opens with maybe 5 or 6 results I am unable to scroll down the results to see the ones at the bottom (below the fold we used to say! and/or the pagination if I have lots of results.) Instead the page underneath the widget scrolls!

On desktop the search widget DOES not extend the full width of the page, so I can move my cursor off to the side if i wanted to scroll the page underneath (which I wouldn't) and if I need to scroll the search results (which I do) I move cursor into centre of page hovering over the search widget results...and they scroll

On mobile the widget DOES extend the full width of the page. Scrolling with my finger DOES NOT scroll the results widget, but instead it scrolls the page underneath the widget, even though the widget is sitting on top of the page (which to me would imply it has correct z-index, otherwise I wouldn't see it!)

My best guess is that it is a JS scrolling issue

other relevant info: My site uses the bootstap v4 framework. The search button spawns a modal/side panel in which the search widget resides. So search panel slides in when i click the search icon, Like I say all working perfectly on desktop.

Also of note, on desktop when you hover over a result it turns a little bar to the left of each result blue, if you move you cursor off the widget to the left of the results the line is no longer blue! indicating that there is some recognition of the hover state which must put focus on the widget. for scrolling rather than the page underneath. On mobile this is not the case. the lines do not turn blue and do not recognise that they are being interacted with via touch screen.

I can also CONFIRM that other modals spawned on the page that have content extending below the fold DO allow me to scroll with my finger, i.e they don;t scroll the page underneath. this indicates it IS NOT an issue with bootstrap modals and/or scrolling but something specific to DatoCMS Search Widget

I don't feel screenshots add anything in this case, so i have tried to just explain the issue in as much detail as I can

**Comment by souljuse** [comment]
Hi @daveharrisonnet, thanks for your report! I tried the widget on one of our websites and I could not find problems with scrolling. It would be useful to see how this issue affects your project. Can you please give us a link to your site here or by writing to support@datocms.com?

**Comment by daveharrisonnet** [comment]
Yeah sure thing. https://unruffled-sammet-a254ca.netlify.com. Try a search for Washers (that will give lots of results!). It is a mobile device issue, in my case android phone using firefox and chrome

**Comment by souljuse** [comment]
Hi @daveharrisonnet, your container <div /> didn't have a height, that is why the overflow wasn't working. Just give add this to your class 

```
{
  height: 100vh;
  overflow: auto;
}
```

![2020-02-14 10 13 10](https://user-images.githubusercontent.com/13051823/74517743-f6645e80-4f12-11ea-95f2-546f0f414cce.gif)
